version: "3.3"

services:
  db:
    image: postgres:12-alpine
    container_name: happy-postgres
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - .env
    logging:
      options:
        max-size: "5m"
        max-file: "4"

  adminer:
    image: adminer
    container_name: happy-adminer
    restart: unless-stopped
    ports:
      - 8080:8080